# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_customer_state_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
