# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-01 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20190430_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
