# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190409_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
