# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190409_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
