# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180905_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='path_to_picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='path_to_picture',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='/category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='/product/'),
        ),
    ]
