# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-26 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20190126_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([]),
        ),
    ]
